name: Maven build

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 11

      - name: Build
        run: mvn --batch-mode clean

#      - name: Build
#        run: mvn --batch-mode compile
#
#      - name: Test and package
#        run: mvn --batch-mode package


